### ISSUE TITLE
IOC fanger should support completely offline operation

### ISSUE THREAD

**Issue by rooterkyberian** [ioc-fang/ioc_fanger#2]
* IOC Fanger version: 1.0.0

### Description

As it is `import ioc_fanger` results in a 2 request to be done to an API, which serves a number of find/replace values, which are later used in all subquentent calls to `ioc_fanger.fang` and `ioc_fanger.defang`.

Due to this - and inability to supply offline copy of this very small data sets (both have only 2 elements at the moment) we had to throw the ioc_fanger out of our dependencies.

Problems we had with the current solution:
- in case of https://ioc-fang.github.io/defanging-dataset/ downtime our project would crash and burn on launch when `import ioc_fanger` is called
- rules could be changed at any time without as knowing
 - inconsistent output of the defang/fang with the one from the past
 - malicious rules could be entered (either DoS our application, or replacing every link with fanged link to something malicous during defang - there is number of possibilities here)

Suggested solution of this issue:
- replace load of dataset on import with lazy load on first use
- allow preloading rule dataset, which should prevent outgoing request altogether

**Comment by fhightower** [comment]
Version 2.0.1 is on pypi which has local datasets.
