### ISSUE TITLE
Standardisation in IP defang position

### ISSUE THREAD

**Issue by geekscrapy** [ioc-fang/ioc_fanger#22]
As below as a reference, the first example shows the decimal before the last octet not being defanged, where-as the second example the middle decimal is not defanged.

Expected output:
192[.]168[.]4[.]2
8[.]8[.]8[.]8

Suggested output:
192[.]168.4[.]2
8[.]8.8[.]8

```
>>> defang('192.168.4.2')
'192[.]168[.]4.2'
>>> defang('8.8.8.8')
'8[.]8.8[.]8'
```

**Comment by fhightower** [comment]
Thanks for reporting this @geekscrapy ! I'll get this fixed.
