### ISSUE TITLE
Clarification on re-fanging

### ISSUE THREAD

**Issue by jakubclark** [ioc-fang/ioc_fanger#25]
I was wondering if the following is intentional:

```python
>>> fang('shotput')
'shttput'
>>> fang('123howp')
'123http'
>>> fang('123howpqwe')
'123httpqwe'
>>> fang('hotpocket')
'httpocket'
```

All of these I would say are false positives. Is this done by design?

I would expect these to remain unchanged, as they are not part of a url.

**Comment by fhightower** [comment]
Hey @jakubclark , thanks for raising this issue. The problem you are reporting was fixed in a recent version of the ioc-fanger library.

Can you try upgrading the package and try again?

You can upgrade the package with:

`pip install ioc_fanger --upgrade`
or 
`pip3 install ioc_fanger --upgrade`

**Comment by jakubclark** [comment]
Great, upgrading the package fixes this.
Thanks for helping out!

**Comment by fhightower** [comment]
No problem, thank you for reporting this issue!
