### ISSUE TITLE
Ability to slurp (command line)

### ISSUE THREAD

**Issue by Maijin** [ioc-fang/ioc_fanger#26]
Other defang/fang tools allows the following `echo "domain.tld | defang"`, that's very powerful when using snippets like `pbpaste | defang | pbcopy`

It would be nice to be able to slurp in `fang`/`defang` utilities.

**Comment by ilyaglow** [comment]
It's pretty easy to implement:
```diff
diff --git a/ioc_fanger/ioc_fanger.py b/ioc_fanger/ioc_fanger.py
index 74988dd..31e187f 100644
--- a/ioc_fanger/ioc_fanger.py
+++ b/ioc_fanger/ioc_fanger.py
@@ -12,6 +12,8 @@ FANG_DATA_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "./fang
 DEFANG_DATA_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "./defang.json"))


+stdin_text = click.get_text_stream('stdin')
+
 def _get_data_from_file(file_path):
     """Get data from the given file path."""
     with open(file_path, 'r') as f:
@@ -53,11 +55,16 @@ def fang(text, debug=False):


 @click.command()
-@click.argument('text')
+@click.argument('text', required=False)
 def cli_fang(text):
     """CLI interface for fanging indicators."""
-    fanged_text = fang(text)
-    print(fanged_text)
+    if text:
+        print(fang(text))
+        return
+
+    if stdin_text:
+        for line in stdin_text:
+            print(fang(line.rstrip('\n')))


 def defang(text):
@@ -78,8 +85,13 @@ def defang(text):


 @click.command()
-@click.argument('text')
+@click.argument('text', required=False)
 def cli_defang(text):
     """CLI interface for defanging indicators."""
-    defanged_text = defang(text)
-    print(defanged_text)
+    if text:
+        print(defang(text))
+        return
+
+    if stdin_text:
+        for line in stdin_text:
+            print(defang(line.rstrip('\n')))
```

But I struggled to make proper tests for it - mocking `sys.stdin` is a pain. And I don't like to decrease the perfect 100% test coverage here :)

**Comment by fhightower** [comment]
Great idea @Maijin and thanks for the help @ilyaglow ! I'll take a look and see what I can do (and try to keep 100% code coverage ;) ).

**Comment by fhightower** [comment]
Thanks again for raising the issue @Maijin  and for the implementation @ilyaglow! It turned out to be pretty easy to test stdin inputs using click: https://click.palletsprojects.com/en/7.x/testing/#input-streams .

**Comment by Maijin** [comment]
Hey that's great, It doesn't seem to install via pip3 though 🧐

**Comment by fhightower** [comment]
Ok, sorry about the wait... I'll take a look.

**Comment by fhightower** [comment]
@Maijin : Are you still having problems installing this package via pip3? I'm not running into any problems.
