### ISSUE TITLE
Handle ip addresses (with commas) fanging 

### ISSUE THREAD

**Issue by bhargava-kush** [ioc-fang/ioc_fanger#35]
When fanging ip address consisting commas, it gives wrong result
`ioc_fanger.fang('ip 23,45,67,89')
'ip 23.45.67.89'`

**Comment by fhightower** [comment]
Thanks for raising this issue @bhargava-kush. What do you expect `ioc_fanger.fang('ip 23,45,67,89')` to produce?

When I run:

```python
import ioc_fanger
ioc_fanger.fang('ip 23,45,67,89')
```
with the latest version of this package, it outputs: `ip 23.45.67.89` (which is what I expect).

**Comment by bhargava-kush** [comment]
@fhightower Thanks for the help, I thought comma-separated numbers will not be treated as IP address.

**Comment by fhightower** [comment]
Ok. Comma-separated numbers are converted to IP addresses because some people "[defang](https://ioc-fang.hightower.space/)" ip addresses using commas.
